services:
  postgres:
    container_name: car_finder_be
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_USER=devkiki
      - POSTGRES_PASSWORD=devkiki77
      - POSTGRES_DB=car_finder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network




volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge