CREATE TABLE app_users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email           VARCHAR(255)                            NOT NULL,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    profile_picture VARCHAR(255),
    is_deleted      BOOLEAN DEFAULT FALSE                   NOT NULL,
    password        VARCHAR(255),
    role            VARCHAR(255),
    CONSTRAINT pk_app_users PRIMARY KEY (id)
);

CREATE TABLE body_types
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    image VARCHAR(255),
    CONSTRAINT pk_body_types PRIMARY KEY (id)
);

CREATE TABLE brands
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_brands PRIMARY KEY (id)
);

CREATE TABLE car_images
(
    car_id BIGINT NOT NULL,
    images VARCHAR(255)
);

CREATE TABLE cars
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    manufacture_date date,
    price            DOUBLE PRECISION,
    location         VARCHAR(255),
    drive_type       VARCHAR(255),
    engine           VARCHAR(255),
    description      VARCHAR(1000),
    features         VARCHAR(1000),
    brand_id         BIGINT,
    body_type_id     BIGINT,
    owner_id         BIGINT,
    user_id          BIGINT,
    CONSTRAINT pk_cars PRIMARY KEY (id)
);

CREATE TABLE reviews
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    stars   INTEGER,
    user_id BIGINT,
    car_id  BIGINT,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

ALTER TABLE app_users
    ADD CONSTRAINT uc_app_users_email UNIQUE (email);

ALTER TABLE brands
    ADD CONSTRAINT uc_brands_name UNIQUE (name);

ALTER TABLE cars
    ADD CONSTRAINT FK_CARS_ON_BODY_TYPE FOREIGN KEY (body_type_id) REFERENCES body_types (id);

ALTER TABLE cars
    ADD CONSTRAINT FK_CARS_ON_BRAND FOREIGN KEY (brand_id) REFERENCES brands (id);

ALTER TABLE cars
    ADD CONSTRAINT FK_CARS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES app_users (id);

ALTER TABLE cars
    ADD CONSTRAINT FK_CARS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_CAR FOREIGN KEY (car_id) REFERENCES cars (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE car_images
    ADD CONSTRAINT fk_car_images_on_car FOREIGN KEY (car_id) REFERENCES cars (id);